### ISSUE TITLE
Link to Issues list on homepage is broken

### ISSUE THREAD

**Issue by rlemon** [ruhoh/ruhoh.js#2]
Links to ruhoh.rb repo. probably should be changed.

**Comment by plusjade** [comment]
@rlemon which links in particular? I'm getting valid links that point here: https://github.com/ruhoh/ruhoh.rb/issues

Also this repo plusjade/ruhoh is a deprecated version of the client-side ruhoh parser (which was the original ruhoh implementation). I've since moved all projects to http://github.com/ruhoh so if you can please post issues there, thanks!

**Comment by rlemon** [comment]
ok http://ruhoh.com/usage/ the link to   

> create a support issue    

after the first code block points to https://github.com/plusjade/ruhoh.rb/issues

**Comment by plusjade** [comment]
Good catch! Thanks, I've pushed the fix just now.
